### ISSUE TITLE
Install extensions / skins by commit id - to avoid taking latest during build which causes issues (GoogleLogin)

### ISSUE THREAD

**Issue by ithiru** [tamil-wiki/mediawiki-docker#10]
Install extensions /skins by commit id - to avoid taking latest during build which causes issues (GoogleLogin)

Please do this for all extensions (currently one for two extensions we are doing).

**Comment by arulrajnet** [comment]
@ithiru I think it's a case by case. Not necessary to pin the commit ID for all the extensions we have used. We are pinning to release branch.  

Better stick to same release version for mediawiki and extensions which is well tested and widely used by community. Upgrade to LTS https://www.mediawiki.org/wiki/Release_notes is even more better. The next LTS is 1.39. Currently, we are in REL1_37

**Comment by ithiru** [comment]
Rather than reacting to issue later, we can prevent from happening, please go ahead and pin to commit id.

**Comment by ithiru** [comment]
CLosing this as Arul suggested
