### ISSUE TITLE
Change Apache to use MPM_Worker instead mpm_prefork which is default

### ISSUE THREAD

**Issue by ithiru** [tamil-wiki/mediawiki-docker#3]
Change Apache to use MPM_Worker instead mpm_prefork which is default

**Comment by ithiru** [comment]
Apache with pre_fork and mod php is not generally recommended.  - https://www.mediawiki.org/wiki/Manual:Performance_tuning#Web_server

**Comment by ithiru** [comment]
Switching to nginx

**Comment by arulrajnet** [comment]
This is no needed w.r.t #8 

Closing this.
