### ISSUE TITLE
Error while login with Google

### ISSUE THREAD

**Issue by arulrajnet** [tamil-wiki/mediawiki-docker#6]
***Given*** The google login configuration are configured
***When*** Login with Google in the login form
***Then*** Redirect to google and authenticated
***Then*** Redirect back to wiki with this error "Oops, there was an error. Please go back and try again. Message: "kid" invalid, unable to lookup correct key"

![2022-04-19_05-13](https://user-images.githubusercontent.com/834529/163893934-06c28993-d076-452e-91f3-73fdc13f0a76.png)

**Comment by ithiru** [comment]
Fixed by getting the right commit from GoogleLogin Repo from mediawiki. Need to repeat this for other extension and skins

**Comment by arulrajnet** [comment]
This issue has been fixed and deployed.
